FIND_PATH(JsonCpp_INCLUDE_DIR json/json.h PATH_SUFFIXES jsoncpp)
FIND_LIBRARY(JsonCpp_LIBRARY NAMES jsoncpp)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	JsonCpp REQUIRED_VARS
	JsonCpp_INCLUDE_DIR
	JsonCpp_LIBRARY)
